# Build with GraalVM
FROM ghcr.io/graalvm/graalvm-community:23 AS builder
WORKDIR /app
COPY . .
RUN ./mvnw clean package -Pnative -DskipTests

# Copy the compiled native binary
FROM busybox:glibc
ENV ENVIRONMENT=prod
WORKDIR /app
COPY --from=builder /app/target/simple-web-crawler-java simple-web-crawler-java
ENTRYPOINT ["./simple-web-crawler-java"]
